-- Personal <-> group financial linking.
--
-- Until now, personal_accounts/personal_transactions and
-- expenses/expense_shares/settlements were two fully disjoint graphs joined
-- only at users.id (see 0012's own comment). That's correct for "how much
-- does everyone owe" (calculateUserBalances/calculatePairwiseDebts in
-- packages/shared already compute that from expenses/expense_shares/
-- settlements alone - nothing new is needed there). What's missing is the
-- *personal* side: when you front a group expense from one of your own
-- accounts, that account really did lose the full amount, but only your own
-- share is real personal spending - the rest is a receivable, not spend.
-- When it's repaid, that's not income, and it must not re-appear as a
-- second expense.
--
-- This migration adds:
--   1. expenses.paid_from_account_id - which of the payer's own accounts
--      fronted the expense (nullable; only meaningful when paid_by = you).
--   2. settlements.from_account_id / to_account_id - which of each party's
--      own accounts the payment left from / landed in.
--   3. Two new personal_transaction_kind values - group_advance (cash left
--      an account to cover a share you'll be repaid) and
--      group_reimbursement (cash came back in repaying that receivable) -
--      kept distinct from expense/income so personal spending/income totals
--      never include them (see packages/shared/src/personalFinance.ts).
--   4. linked_expense_id / linked_settlement_id / linked_group_id on
--      personal_transactions, so the UI can show "From <group>" and so
--      deleting/editing the source expense/settlement correctly removes or
--      regenerates the mirrored personal transaction rows instead of
--      leaving stale phantom cash movements behind.
--
-- The RPCs that actually write these new columns (create_group_expense,
-- update_group_expense, record_settlement, confirm_settlement_receipt) are
-- defined in 0015 - a newly added enum value cannot be referenced by a
-- function body created in the same transaction, so they're kept as a
-- separate migration.
--
-- The three new linking columns are additionally locked down at the column
-- privilege level so they can only ever be set via those RPCs - never by a
-- plain client-side insert/update - so a linked expense/settlement can never
-- exist without its personal_transactions mirror actually having been
-- written in the same transaction.

-- ─────────────────────────────────────────────────────────────────────────
-- New columns
-- ─────────────────────────────────────────────────────────────────────────

alter table public.expenses
  add column if not exists paid_from_account_id uuid references public.personal_accounts (id) on delete set null;

comment on column public.expenses.paid_from_account_id is
  'The personal account (owned by paid_by) that fronted this expense''s full amount, if linked. Only ever set by create_group_expense()/update_group_expense().';

alter table public.settlements
  add column if not exists from_account_id uuid references public.personal_accounts (id) on delete set null,
  add column if not exists to_account_id uuid references public.personal_accounts (id) on delete set null;

comment on column public.settlements.from_account_id is
  'from_user''s own account this payment left from, if linked. Only ever set by record_settlement().';
comment on column public.settlements.to_account_id is
  'to_user''s own account the reimbursement landed in. Usually set later than from_account_id, since only to_user can attribute it - via confirm_settlement_receipt().';

alter type public.personal_transaction_kind add value if not exists 'group_advance';
alter type public.personal_transaction_kind add value if not exists 'group_reimbursement';

alter table public.personal_transactions
  add column if not exists linked_expense_id uuid references public.expenses (id) on delete cascade,
  add column if not exists linked_settlement_id uuid references public.settlements (id) on delete cascade,
  add column if not exists linked_group_id uuid references public.groups (id) on delete set null;

comment on column public.personal_transactions.linked_expense_id is
  'Set on rows auto-generated by create_group_expense/update_group_expense. Cascades on delete so removing/editing the source expense cleans up its mirrored personal transactions rather than leaving a phantom cash movement.';
comment on column public.personal_transactions.linked_settlement_id is
  'Set on rows auto-generated by record_settlement/confirm_settlement_receipt. Cascades on delete for the same reason as linked_expense_id.';
comment on column public.personal_transactions.linked_group_id is
  'Denormalized for "From <group>" UI navigation without an extra join. Set null (not cascaded) if the group itself is later deleted - the personal transaction history still belongs to the user.';

create index if not exists personal_transactions_linked_expense_id_idx on public.personal_transactions (linked_expense_id) where linked_expense_id is not null;
create index if not exists personal_transactions_linked_settlement_id_idx on public.personal_transactions (linked_settlement_id) where linked_settlement_id is not null;

-- ─────────────────────────────────────────────────────────────────────────
-- Column-level lockdown: these five columns may only be written by the RPCs
-- in 0015 (which run as SECURITY DEFINER and so aren't subject to these
-- grants), never by a direct client insert/update against the tables.
-- Everything else about these tables is untouched - existing direct
-- insert/update/delete of unrelated columns keeps working exactly as before.
-- ─────────────────────────────────────────────────────────────────────────

revoke insert (paid_from_account_id), update (paid_from_account_id) on public.expenses from authenticated;
revoke insert (from_account_id, to_account_id), update (from_account_id, to_account_id) on public.settlements from authenticated;
revoke insert (linked_expense_id, linked_settlement_id, linked_group_id), update (linked_expense_id, linked_settlement_id, linked_group_id) on public.personal_transactions from authenticated;
